// <auto-generated />
using InsuranceOffer.Test.Case.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsuranceOffer.Test.Case.DataLayer.Migrations
{
    [DbContext(typeof(InsuranceDBContext))]
    partial class InsuranceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsuranceOffer.Test.Case.DataLayer.Model.CustomerInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Plaka");

                    b.Property<string>("RuhsatSeriKodu");

                    b.Property<string>("RuhsatSeriNo");

                    b.Property<string>("TCKN");

                    b.HasKey("ID");

                    b.ToTable("CustomerInfo");
                });

            modelBuilder.Entity("InsuranceOffer.Test.Case.DataLayer.Model.CustomerInsuranceOffers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerID");

                    b.Property<string>("FirmaAdi");

                    b.Property<string>("FirmaLogosu");

                    b.Property<string>("Plaka");

                    b.Property<string>("TeklifAciklamasi");

                    b.Property<string>("TeklifTutari");

                    b.HasKey("ID");

                    b.ToTable("CustomerInsuranceOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
